### PR TITLE
Compatible 4.8

### LINKED ISSUE #9: Make it work with ocaml 4.8 ?
Hi,
I'd need to have flow-parser working with OCaml 4.8, is it possible to make it work with some work ? Of course, pointed in the right direction I'd happily write a PR :)
Thanks !

### PR DESCRIPTION
**Pull request by giltho**
This tries to have flow-parser compatible with 4.8.

@jordwalke, you removed compatiblity with 4.8 at some point because apparently omp wasn't happy with vendored stuff, maybe the reason is still there and I haven't fixed it ? But it does compiled with 4.8.

I upgraded ocaml ppx_tools_versioned from 5.2 to 5.2.3 (which is what most changes are), added stdlib-shims because Pervasives was deprecated, the esy.lock upgraded for some reason too.

(fixes #9)

### CODE REVIEW

**Comment by giltho** [comment]
Update: I've used this on a project and it seems to all be working fine

**Comment by jordwalke** [comment]
But is this still compatible with older ocamls now?

**Comment by giltho** [comment]
@jordwalke, I wrote a tiny action for esy (no caching or anything), I thought this project is a nice place to experiment with it.
It seems to build nicely on every version in the matrix
```yaml
matrix:
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
        ocaml-version: [ '4.9.0', '4.8.1000', '4.7.1004', '4.6.1000' ]
```
Feel free to add versions to the matrix or revert the commit if you want to stay on travis (or ask me and I'll revert it)
https://github.com/giltho/flow-parser/commit/43a89f4b15b805d86ac24cc08233bf28802b3470/checks?check_suite_id=416233658

**Comment by giltho** [comment]
@jordwalke After rethinking about it, I'm not satisfied with my esy story for github action yet and it had nothing to do with this PR anyway, so I killed that commit. This PR only contains update to have flow-parser working in ocaml 4.8.1.

Long story short : it compiles on every platform with `'4.9.0', 4.8.1000', '4.7.1004', '4.6.1000'`, I use this version with ocaml 4.8 daily and so far I've had no issue.

**Pull request closed without merging**
